AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Test ELB 
Parameters:
  PublicLBSubnet1:
    Description: ID of the Subnet for the public load balancer
    Type: List<AWS::EC2::Subnet::Id>
  PublicLBSubnet2:
    Description: ID of the Subnet for the public load balancer
    Type: List<AWS::EC2::Subnet::Id>
  PublicLBSubnet3:
    Description: ID of the Subnet for the public load balancer
    Type: List<AWS::EC2::Subnet::Id>    
  LoadBalancerTerminationProtection:
    Description: Instance Termination Protection.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  VpcId:
    Description: VPC ID
    Type: String<AWS::VPC::Id>
  TargetInstance1:
      Description: Target instance ID
      Type: String<AWS::EC2::Id>
  TargetInstance2:
      Description: Target instance ID
      Type: String<AWS::EC2::Id>
  TargetInstance3:
      Description: Target instance ID
      Type: String<AWS::EC2::Id>

Resources:
 EIP1:
  Type: AWS::EC2::EIP
  Properties:
    Domain: VPC
 EIP2:
  Type: AWS::EC2::EIP
  Properties:
    Domain: VPC
 EIP3:
  Type: AWS::EC2::EIP
  Properties:
    Domain: VPC
 TestELB1:
  DependsOn:
   - EIP3
   - EIP2
   - EIP1
  Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
  Properties:
     Name: TestELB1
     Scheme: internet-facing
     Type: network
     LoadBalancerAttributes:
     - Key: deletion_protection.enabled
       Value: !Ref LoadBalancerTerminationProtection
     - Key: access_logs.s3.enabled
       Value: False
     SubnetMappings:
       - AllocationId:
           Fn::GetAtt:
           - EIP1
           - AllocationId
         SubnetId:
           Fn::Select:
           - '0'
           - Ref: PublicLBSubnet1
       - AllocationId:
          Fn::GetAtt:
          - EIP2
          - AllocationId
         SubnetId:
           Fn::Select:
           - '0'
           - Ref: PublicLBSubnet2
       - AllocationId:
          Fn::GetAtt:
          - EIP3
          - AllocationId
         SubnetId:
           Fn::Select:
           - '0'
           - Ref: PublicLBSubnet3
     Tags:
     - Key: "Name"
       Value: "TestELB1"

 TestELBHTTPTargetGroup:
  Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
  Properties:
   HealthCheckIntervalSeconds: 10
   HealthyThresholdCount: 3
   TargetType: instance
   UnhealthyThresholdCount: 3
   VpcId: !Ref VpcId
   Port: 80
   Protocol: TCP
   Targets:
    - Id: 
       !Ref TargetInstance1
      Port: 80
    - Id: 
       !Ref TargetInstance2
      Port: 80
    - Id: 
       !Ref TargetInstance3
      Port: 80
   Tags:
    - Key: "Name"
      Value: "TestELBHTTPTargetGroup"

 TestELBHTTPListener:
  Type: "AWS::ElasticLoadBalancingV2::Listener"
  Properties:
    DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref TestELBHTTPTargetGroup
    LoadBalancerArn: !Ref TestELB1
    Port: "80"
    Protocol: TCP
 


